name: 0jo blog build and deploy

on:
  push:
    branches: [ "master" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    #node 버전 지정
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - run: npm install --legacy-peer-deps

    #npm build
    - name: Build
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.ACTION_KEY }}
        publish_dir: ./public
